import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-full  flex justify-center min-h-screen leading-relaxed tracking-wide pt-10`}>
        <div className="lg:w-1/2 flex ">
          <div><Navbar /></div>
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}